### ISSUE TITLE
關於歲差的計算方式之疑問

### ISSUE THREAD

**Issue by kanasimi** [ytliu0/ChineseCalendar#1]
感謝您釋出這個工具
您提到
> 歲差採用Vondrák等人於2011年建立的歲差模型Vondrák計算。

網路上面另外可以找到唐凯的
[A long time span relativistic precession model of the Earth](https://iopscience.iop.org/article/10.1088/1674-4527/15/4/010/pdf)
請問兩者間的精確度以何者較佳呢

**Comment by ytliu0** [comment]
您好! 感謝您提出的問題。

我已看了您附上的文章。那篇文章的歲差計算計及廣義相對論效應，自然比Vondrák等人的模型更準確，但文章第四節說相對論效應的修正在幾十萬年後才重要(見其圖9和圖10)。文章說他們模型的有效年限是公元2000年前後一百萬年，也比Vondrák等人模型的有限年限(公元2000年前後二十萬年)長。如果把年限限制在公元2000年前後幾千年間，則他們的模型與Vondrák等人模型差異不大。

有一點要注意:Vondrák等人的模型和唐凱等人的模型都是先用數值積分法計算，然後用多項式及三角函數級數來擬合數據，所以主要的誤差其實是他們給出的近似公式與數值積分結果的差異。Vondrák等人的近似公式在公元2000年前後幾千年間的差異不超過10"。唐凱等人的模型就不大清楚，因為從他們的圖5-圖8只能看出他們的近似公式與數值結果在幾十萬年間的差異一般少於100"，在幾千年間的差異則難以從圖中看出。我的估計是和Vondrák等人的近似公式的精度相約。

總結以上資料，如果要計算涵蓋幾十萬年的歲差，就應用唐凱等人的模型。如果只計算涵蓋幾千年的歲差，兩者的模型精度應該差不多。

**Comment by kanasimi** [comment]
感謝您的回應
小弟這邊也做了一個類似的工具供您參考
[紀年轉換工具.](https://kanasimi.github.io/CeJS/_test%20suite/era.htm)
小弟想要在其中匯入您現成的古六曆資料
不曉得是否可以呢

**Comment by ytliu0** [comment]
感謝您告知您的轉換工具。其實您的資料比我豐富，而且似乎得到高人指點,，比我這只花幾個月時間自己看書學習中國古代曆法要強。其實我應該向您學習才是，如果您發現這裡的資料有錯誤，還請指正。

至於這裡的古六曆，我們的工具都是開放源，我當然樂意分享。您想怎樣匯入? 如果需要幫忙，就發電郵給我吧。

**Comment by kanasimi** [comment]
謝謝您的回應

不曉得這邊的古六曆，是否有可能匯出成
1. 第一欄是當年的歲首JDN
2. 第二欄是所有當年月份的日數

這樣的形式呢？例如 春秋曆:
```
1457728	29;30;29;30;29;30;30;29;30;29;30;29
```

若是您發現 紀年轉換工具.有什麼錯漏或可以改進的地方
很歡迎您告知小弟
謝謝

**Comment by ytliu0** [comment]
我開了新的 issue 專門討論古六曆的代碼，請到那裡看我的回應。

**Comment by ytliu0** [comment]
由於這裡的討論已偏離了原先的歲差主題，我開了新的issue專門討論古六曆的代碼，請您到那裡參看代碼吧。

**Comment by kanasimi** [comment]
謝謝
