### ISSUE TITLE
现有数据计算出来的节气时间随着年份推移偏差会越来越大吗?

### ISSUE THREAD

**Issue by Aquarian-Age** [ytliu0/ChineseCalendar#11]
用TDBtimes_extended.txt的数据写了一个自己用的历法纪年软件
在`不计算润秒`的前提下节气时刻和寿星天文历法对比相差基本就是没有计算润秒的数值
到2600年(虽然今生用不到这数据)的时候节气时间和寿星天文历法差了将近半个小时 随着时间的推移 这个差值会越来越大
这是因为没有计算润秒还是因为数据本身就是这样的呢 ？方便修正吗?谢谢

**Comment by ytliu0** [comment]
这点我在[这pdf文件](https://ytliu0.github.io/ChineseCalendar/docs/sunMoon_simp.pdf)第8节有说明。《农历的编算和颁行》(GB/T 33661-2017)文件明确说明朔和二十四节气的时刻用北京时间(UTC+8)，而TDBtimes_extended.txt数据的时间是TDB，当然要计算闰秒，但是闰秒没有固定规则，未来的闰秒要根据观测数据不断更新。

**Comment by Aquarian-Age** [comment]
好吧 谢谢...
