### ISSUE TITLE
关于年表中汉献帝中平年号的疑问

### ISSUE THREAD

**Issue by zizicici** [ytliu0/ChineseCalendar#13]
Hi，ytliu0，你好。

我在算日期的时候有一点疑惑。特像你请教。

根据《后汉书》记载，中平六年十二月戊戌，“詔除光熹、昭寧、永漢三號，還復中平六年。” （reference https://ctext.org/hou-han-shu/xiao-xian-di-ji ）

https://ytliu0.github.io/ChineseCalendar/era_names_simp.html 而此处汉献帝，中平六年对应的时间是公元 189 年。

但是用 https://ytliu0.github.io/ChineseCalendar/ 计算出来的中平六年十二月戊戌，似乎只有闰十二月的日子里有戊戌，这时候也已经是公元 190 年 2 月 19 日。（距离下一年正月初一也只差四日）

如果记载没问题的话，也许应该认为中平六年是在新年前几天被重新恢复的？

**Comment by ytliu0** [comment]
您好!

根据您用的《后汉书》资料，"十二月戊戌"在"十一月癸酉"之后。单从历日而论，戊戌在癸酉之后25日或85日，张培瑜《三千五百年历日天象》、汪曰桢《历代长术辑要》、《通鉴目录》、陈垣《二十史朔闰表》、薛仲三和欧阳颐《两千年中西历对照表》都载十一月癸酉朔，闰十二月壬申朔，而历法朔日必在实朔一两日内，十一月必含冬至，因此十一月癸酉朔应该没有错，这样一来如果《后汉书》和那五本书的资料无误的话，"十二月戊戌"只能在"十一月癸酉"之后85日，就是闰十二月廿七。如果是这样的话《后汉书》应该写"闰月戊戌"才对，也有可能那五本书的历日资料不对，也许当年是闰十一月，"十二月戊戌"是十二月廿七日，也是新年前几天。我不是专家，无法判断谁是谁非。这里东汉的日历是根据《三千五百年历日天象》的资料编算。

**Comment by ytliu0** [comment]
搜查百度，看到了范鹏伟在2013年的一篇硕士论文[《后汉书历日订误》](https://www.doc88.com/p-5929588374949.html)，文中引了清人黄山"(后汉书)历日踳驳之处不胜枚举"之言。其中第65页的文字可供参考:

> 《后汉书‧孝献帝纪》载: "(中平六年)十一月癸酉，董卓为相国。十二月戊戌，司徒黄琬为太尉，司空杨彪为司徒，光禄勋荀爽为司空。"
>中平六年十二月癸卯朔，此月无戊戌日。
>按，《孝灵帝纪》载:"夏四月丙午朔，日有食之。" 《续五行志》同。四月丙午朔，以此推之，十二月确无戊戌日。《后汉纪》董卓为相国与黄琬等转任同在十月，以同月例之，疑"十二月"为衍，或"戊戌"有误。

这文字逻辑上有问题。首先，以"四月丙午朔"推断"十二月确无戊戌日"似嫌草率，未考虑中间可能有闰月。其次是看不出怎样从"董卓为相国与黄琬等转任同在十月"推出"十二月为衍"或"戊戌有误"的结论。于是查[《后汉纪》孝灵皇帝纪下卷第二十五](https://www.diyifanwen.com/guoxue/houhanji/063532094250635326029643_12.htm)，得知《后汉纪》确是载董卓为相国与黄琬等转任在同一月，原文写十月，校者认为是十一月之误。如果十一月是对的话，就可推出"十二月为衍"的结论。

我认为十一月癸酉朔应该是没有错的，用东汉四分历也算出该年闰十二月，既然有学者指出《后汉书》的历日有不少错误，我也倾向赞同《后汉书‧孝献帝纪》的那个历日有误。
