### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by LuoZijun** [ytliu0/ChineseCalendar#15]
> 现在中国各地采用的时间是东八区的区时，比UTC迟八小时，一般以UTC+8表示，也称为北京时间或中国标准时。

这里面的 `比UTC迟八小时` 应该是 `比UTC早八小时` 吧？

出现的位置:

https://github.com/ytliu0/ChineseCalendar/blob/900d8019e0ba04bb6214a34a650be531dab89f27/src/rules_simp.html#L98

**Comment by ytliu0** [comment]
是迟是早看你怎样定义，9:00 与 1:00 哪个是早? 北京时间 9:00 与 UTC 1:00 其实是指相同的时刻，数字上却是UTC的时刻加上8小时。

但是如果你问 2023年1月1日北京时间0:00 与 2023年1月1日 UTC 0:00 哪个早? 则毫无疑问是2023年1月1日北京时间0:00 早，因为那时刻相当于 2022年12月31日 UTC 16:00。

为了避免混淆，下次修改时或会改为:
> 现在中国各地采用的时间是东八区的区时，与UTC數字上相差八小时(例如北京时间9:00相当于 UTC 1:00 )，一般以UTC+8表示，也称为北京时间或中国标准时。

这样就不会有误会了吧。

**Comment by LuoZijun** [comment]
明白了，谢谢解答 :)
