### ISSUE TITLE
关于朔和初一没匹配上的疑问

### ISSUE THREAD

**Issue by melon** [ytliu0/ChineseCalendar#16]
偶然间发现813年3月的日历里，月相里朔是 6d19h54m ，按理说初一应该是3月6日，但实际初一是 3月7日，出现这个情况是为什么那？

**Comment by ytliu0** [comment]
这样的情况在古代的日历很常见，原因至少有二。

一： 6d19h54m 等年历网页列出的合朔时刻是用现代历表计算的结果，所用的时间是東经120度地方平时，古代历法计算合朔的方法与现代不同，而且是用当时天文观测站的地方视时（即地方真太阳时）。

二： 自唐《麟德历》起引入进朔法，如果合朔时刻在18点后，可以虚进一日。此法在唐、五代、两宋和元初都使用，自元《授时历》后癈除。

813年二月朔的情况很可能是进朔法的结果。

**Comment by melon** [comment]
> 这样的情况在古代的日历很常见，原因至少有二。
> 
> 一： 6d19h54m 等年历网页列出的合朔时刻是用现代历表计算的结果，所用的时间是東经120度地方平时，古代历法计算合朔的方法与现代不同，而且是用当时天文观测站的地方视时（即地方真太阳时）。
> 
> 二： 自唐《麟德历》起引入进朔法，如果合朔时刻在18点后，可以虚进一日。此法在唐、五代、两宋和元初都使用，自元《授时历》后癈除。
> 
> 813年二月朔的情况很可能是进朔法的结果。

原来如此，感谢解疑~
