### ISSUE TITLE
关于更始元年的月份次序的疑问

### ISSUE THREAD

**Issue by melon** [ytliu0/ChineseCalendar#17]
从 [公 历 和 农 历 日 期 对 照](https://ytliu0.github.io/ChineseCalendar/index_simp.html) 这里搜23年，可以看到23年的农历年月的顺序是 正月、二月、三月、...、十月、十一月、十二月、十二月。正月之后是二月，并且有两个十二月。

关于这年的月份，有两个疑问：

1.有地方的资料说这一年应该有两个十月，而不是两个十二月，例如 [网页1](http://www.itmao.com/html/404.html)，[网页2](http://bbs.nongli.net/dispbbs_2_19443_24_next.html)，

> 5)公元23年，淮阳王改元更始，复用寅正，以地皇十一月为更始1年的十月，故该年有两个十月。

>  1、中央研究院公元23年是两个十月，寿星万年历中是两个十二月。

应该哪个是正确的呢，或者说这个目前还存在争议？

2.看资治通鉴里更始元年部分的记载（[Wikipedia](https://zh.wikisource.org/zh-hans/%E8%B3%87%E6%B2%BB%E9%80%9A%E9%91%91/%E5%8D%B7039)）， 里面某几个月份的朔日跟日历里对不上，但是有个奇怪的地方就是，日历里某个月份的下一月的朔日，刚好都能跟资治通鉴里的对上。例如资治通鉴里记载更始元年：

> 二月，辛巳朔

> 六月，己卯朔

> 九月，戊申朔

但日历里却是：三月，辛巳朔；七月，己卯朔；十月，戊申朔。如果史料对的话，反过来推断，更始元年的正月之后，有没有可能是一月，而不是二月？建寅月要么是正月、要么是一月？

**Comment by ytliu0** [comment]
我不是这方面的专家，恐怕不能肯定回答这问题。

本网页的公元23年资料取自张培瑜《三千五百年历日天象》，该书23年载两个十二月。

以下的论述是我的见解，我不是这方面的专家，也未有深入研究这问题，所以仅供参考。

新朝于地皇四年覆灭，刘玄被拥立为帝，改元更始元年，恢复寅正。所以地皇四年和更始元年有重叠，我认为地皇四年和更始元年可视为独立的纪年系统。地皇四年用丑正，更始元年用寅正，故地皇四年二月等同于更始元年正月，地皇四年三月等同于更始元年二月……地皇四年十二月是更始元年十一月。

如果公元23年的中历全用地皇四年来纪，朔闰表是
正壬午, 二壬子, 三辛巳, 四辛亥, 五庚辰, 六庚戌, 七己卯, 八己酉, 九戊寅, 十戊申, 十一丁丑, 十二丁未

如果公元23年的中历全用更始元年来纪，朔闰表是
正壬子, 二辛巳, 三辛亥, 四庚辰, 五庚戌, 六己卯, 七己酉, 八戊寅, 九戊申, 十丁丑, 十一丁未, 十二丙子

所以更始元年的朔闰應該沒有争议，问题是中国在23年什么时候废地皇四年，改用更始元年? 史书是否有统一的标准，我就不知道了。出现两个十月和两个十二月的说法，可能就是何月改用更始元年的分歧。资治通鉴明显在新朝未亡时已用更始元年纪日了，即在更始年号建立前已用更始元年追溯以前的日期，这样做的好处是不需杂用两套纪年系统，叙述历史比较方便。

我认为在不确定的情况下，不妨用双重纪日法，即地皇四年和更始元年并用。例如公元23年11月10日的中历日期是地皇四年十一月乙酉，也是更始元年十月乙酉，这样便很清楚了。

**Comment by ytliu0** [comment]
刚刚翻看了汪曰桢[《历代长术辑要》](https://cnkgraph.com/Book/%E5%AD%90%E9%83%A8/%E5%A4%A9%E6%96%87%E7%AE%97%E6%B3%95%E9%A1%9E/%E6%AD%B7%E4%BB%A3%E9%95%B7%E8%A1%93%E8%BC%AF%E8%A6%81/7142)，此书[卷四](https://c.cnkgraph.com/eBooks/%e5%9b%9b%e5%ba%ab%e4%b9%8b%e5%a4%96/%e6%ad%b7%e4%bb%a3%e9%95%b7%e8%a1%93%e8%bc%af%e8%a6%81%20%e6%b8%85%20%e6%b1%aa%e6%9b%b0%e6%a5%a8%e6%92%b0/%e5%9b%9b.pdf)对此有清楚说明:

> 汉淮阳王更始元，新地皇四。

> 汉正(建寅)壬子, 二辛巳, 四庚辰, 六己卯, 八戊寅, 十丁丑, 十二丙子朔。

> 新正(建丑)壬午, 三辛巳, 五庚辰, 七己卯,  九戊寅, 十一丁丑朔。

然后指出《后汉纪》、《汉书·王莽传》、荀氏《汉纪》、资治通鉴及《续汉书·天文志》出现的朔日差异乃是用不同正朔之故。

> 此年汉仍用寅正与新用丑正异，今两列之。

可见《历代长术辑要》的说法与我上面的说法一致。不同史书在此年采用不同的正朔，因此出现朔日差异，但是这差异是表面的，只要注明是用新朝的地皇四年还是汉的更始元年就不会有问题了，我认为用双重纪年则更好。
