### ISSUE TITLE
请求添加古代历法五星运行相关内容

### ISSUE THREAD

**Issue by 1284685832** [ytliu0/ChineseCalendar#19]
对我国古代历法很感兴趣，这里是我找到的介绍最全面、丰富、精确的地方，可惜的是没有介绍到古代历法中关于行星的内容，略微有些遗憾。

能否在主页介绍相关内容？

或者，提供现代高精度五星运行相关数据来源，以供爱好者推算。

又或者，给个能查到相关数据的网址也行。

谢谢大佬。

**Comment by ytliu0** [comment]
中国古代五星的具体算法我未有时间涉猎，短期内不可能加入这些内容。

清朝以前的算法应可从历代的天文律历志找到，也可从介绍古代历法的书籍找到，不过听说算得很不准，听说往往有十度偏差，到了清朝引进西方的算法后才有改善，不过当时也只是引进了十六世界第谷的算法，精度不高。清朝的算法可参考康熙末年编的[《御制历象考成》](https://cnkgraph.com/Book/%E5%AD%90%E9%83%A8/%E8%A1%93%E6%95%B8%E9%A1%9E/%E5%BE%A1%E8%A3%BD%E6%AD%B7%E8%B1%A1%E8%80%83%E6%88%90/2471)，网上好像有人作了注解，可以搜索一下。

现代的高精度算法是用数值积分法计算，主要用途是策划派探测器探索太阳系天体。这些高精度历表的数据可免费下载，也有网站提供数据，例如 JPL 的 Horizons 网站:
https://ssd.jpl.nasa.gov/horizons/
俄国的网站:
https://iaaras.ru/en/dept/ephemeris/online/
法国网站:
https://ssp.imcce.fr/forms/ephemeris
