### ISSUE TITLE
请教：后汉书中所采用的历法与您「公历和农历日期对照」表中的历法以致吗？

### ISSUE THREAD

**Issue by xwa130** [ytliu0/ChineseCalendar#21]
Hi @ytliu0 非常感谢您的工作！

我在确认一个天文现象，后汉书中光武帝纪第一下记载**光武帝七年三月癸亥**日发生了**日有食之**，**日月薄食**
<img width="906" alt="Screenshot 2024-03-18 at 15 27 02" src="https://github.com/ytliu0/ChineseCalendar/assets/26393079/3a2ce9d2-ed19-4884-8de1-c79a74db61c5">

在您[公历和农历日期对照](https://ytliu0.github.io/ChineseCalendar/index_simp.html)中我发现这个日子对应的是
<img width="795" alt="Screenshot 2024-03-18 at 15 20 51" src="https://github.com/ytliu0/ChineseCalendar/assets/26393079/df98f4a5-4a21-49f6-b403-6dc500e9a970">
格里高利历**31年4月30日**，**农历三月二十**。

但是农历三月二十月由盈转亏，看样子不可能发生**日有食之**吧。

请问您知道后汉书这里所采用的是什么历法吗？可以直接对应到您创建的那个网页上的日历吗？感谢您的回答！

**Comment by xwa130** [comment]
抱歉是我疏忽了，是三月癸亥日，对应的是公历5月10日，确实有一次[日食](http://ytliu.epizy.com/eclipse/one_solar_eclipse_general.html?ybeg=1&ind=75&DE=431)，打扰了。

再次鸣谢您的工作！

**Comment by ytliu0** [comment]
后汉书:

> 癸亥晦，日有食之

"晦"是指朔之前的一日，三月晦，就是三月最后一日。晦日见日食，在古时用平朔法编历时并不罕见。

后汉书记载的那次日食，京师洛阳的见食情况可从[此网页](http://ytliu.epizy.com/eclipse/one_solar_eclipse_local.html?ybeg=1&ind=75&DE=431&lam=112.45361&phiV=34.68361&elevation=149&tz=8&dT=10108.92&k2=default)看到。初亏在早上7:34，食甚在8:50，复圆在10:16 (全部时刻用当地的真太阳时)，食甚时有73%太阳直径(64%太阳面积)被遮掩。

**Comment by xwa130** [comment]
@ytliu0 谢谢先生的回复！

我在查考圣经中
路加福音23章44节「那时约有午正，遍地都黑暗了，直到申初，」

有人说在光武帝七年，即我上述引用的史料中所记载的和圣经中「遍地都黑暗了」是同一件事，我就查考了一下，看样子不是同一件事，因为耶稣被钉十字架是在逾越节，按着犹太历是在14日，正是月望的时候，而这里记载的是在晦朔之时。

所以望月发生日食，只能是超自然神迹了。如果您有什么见解，请先生不吝赐教。

其实有一个小疑惑，就是按理说日食不是稀罕的天象，但是刘秀在这里却「不听事五日」且一个月后下罪己诏，「大赦天下」，有点不合常理。不懂其中缘由。请先生不吝赐教。

再次谢谢您的辛劳工作并慷慨开源您的代码！

**Comment by ytliu0** [comment]
路加福音的那段文字我未有研究，但照字面意思似乎是说"遍地都黑暗了"是由午正至申初，也就是三小时。日全食時"遍地黑暗"也不过几分钟的时间，如果那段文字所述真有其事，那必定不是日食，也许是奇异气象。

至于刘秀的情况，我相信是受到天命论的思想影响。古时人们相信君权天授，如果上天对统治者不满，会用一些特殊异象例如日月食、彗星、地震、旱灾、水灾等警告统治者。今天看来虽然是迷信，但是只要有足够多人相信，你即使不信也不能不重视，因为会有野心家利用这些异象宣扬现政权已失天命，密谋造反，所以统治者不能对这些异象无动于衷。刘秀当时是真的相信天命论，还是在演一场政治戏，我就不知道了。

人们后来能预报日月食，按理说日月食不应算是特异天象，但是准确预报日月食涉及的天文计算很复杂，不是古代天文学家能掌握的，所以有时预报不准，当在沒有預報的日子发生日月食或預報與實際天象有重大偏差，就会被视为是上天预警。所以准确计算日月食在古代十分重要，用现代的说法，能否准确预报日月食，涉及国家安全。中国古代历法不断修改，就是为了改善日月食的预报精度。

**Comment by xwa130** [comment]
哈哈，感谢您的回复，向您学习了！
