### ISSUE TITLE
请教2033年置润问题

### ISSUE THREAD

**Issue by gofmt** [ytliu0/ChineseCalendar#5]
感谢提供的TDB数据。根据数据自己写了一个计算程序。发现2033置润确实和您博客里面提到的一样。是错误的我现在程序显示2033润月月份在农历7月。请问您置润的方法是根据月份内不含中气吗？如果不是的话这个置润该怎么计算呢？谢谢。

**Comment by ytliu0** [comment]
您好!

现代农历的置闰法应根据2017年发布的《农历的编算和颁行》文件(编号GB/T 33661-2017)，我在[此网页](https://ytliu0.github.io/ChineseCalendar/rules_simp.html#rules)转述了文件所述的法则。有关置闰的法则是:

**如果从某个农历十一月开始到下一个农历十一月之间有十三个农历月（包括第一个十一月但不计第二个十一月），则取其中最先出现的一个不包含中气的农历月为农历闰月。**

我也在[农历编算例子](https://ytliu0.github.io/ChineseCalendar/examples_simp.html)例二展示了编算2033年农历的方法，其后也指出了为什么以前很多编历者都弄错了这年的农历月份。**闰七月是错的，闰十一月才正确。**

如果您仍有怀疑，请参考刘宝琳和刘婷婷编的《百年历表及日月食(2001-2100)》的前言:

'历年来，中国科学院紫金山天文台出版的"万年历"中由本人(刘宝琳)所主编的，先后共有七种:在科学普及出版社出版的有四种，在科学出版社出版的有两种，香港商务印书馆出版的一种。特别是1984年在科学普及出版社出版的《新编万年历(修订本)》，直接或间接成为坊间"万年历"的主要依据。《新编万年历(修订本)》原来登载2033年农历"闰七月"，1986年重印时改为农历"闰十一月"。坊间的"万年历"凡是根据《新编万年历(修订本)》"新版本"的，都按2033年农历"闰十一月"编排；而根据"旧版本"的，则按2033年农历"闰七月"编排。以至于，坊间的"万年历"对于2033年的农历有"闰七月"和"闰十一月"两种不同排法。**在这里要特别指出，2033年按农历"闰十一月"编排是正确的。**'

**Comment by gofmt** [comment]
感谢回复 没有怀疑的意思 可能我计算方法有问题吧 回头看看我的计算方法修正一下 谢谢

**Comment by ytliu0** [comment]
2033年的置闰问题似乎争论颇多，我以前也搞错了，看到了刘宝琳那段前言，才知道连紫金山天文台出版的书藉也出过错，可见这问题不简单。但是到了2017年发布了《农历的编算和颁行》文件后，法则都说清楚了，不应再有争论。

这些法则隐含了一个重要信息:不是所有无中气的月份都是闰月。有没有闰月先要看前后两个十一月(含冬至的月份定为十一月)相隔的月数是十二还是十三，是十三才有闰月，而闰月是取冬至后第一个不含中气的月份。

我在[农历编算例子](https://ytliu0.github.io/ChineseCalendar/examples_simp.html)指出从2033年到2034年间有三个月不含中气，但只有一个是闰月。2032年十一月与2033年十一月之间只有十二个月，所以中间没有闰月，虽然七月后的那个月不含中气，但是不能闰。2033年十一月到2034年十一月间有十三个月，所以有闰月;当中有两个月不含中气，最先出现的无中气月是十一月之后的那个月，所以是闰十一月，虽然十二月之后的那个月也不含中气，但不能再闰。

刚才忘了问您，您说的博客是指什么呢?我没有在博客写过文章啊。

**Comment by gofmt** [comment]
嗯 这么一说我思路明白了 估计是我没有计算全年12还是13月 只是单纯判断了那个月不含中气。博客就是您的[农历编算法则](https://ytliu0.github.io/ChineseCalendar/rules_simp.html#pmo86) 在网上偶然搜到后启发很大 感谢分享。

**Comment by ytliu0** [comment]
啊，原来是那网页。没想到现在还有不少人对传统历法感兴趣。感谢!
