### ISSUE TITLE
關於曆法精度的一個疑問

### ISSUE THREAD

**Issue by ghost** [ytliu0/ChineseCalendar#7]
作者您好，首先感謝您提供的公曆和農曆日期對照 Project，我也是個古曆法研究愛好者，但是非專業人士，有個問題一致困擾我，倘若作者瞭解，還希望不吝賜教。

問題是這樣的，我們都知道根據天文算法計算日曆會有一定程度的誤差，以計算二十四節氣為例，其精度可以精確到毫秒，打個比方說某年的“大雪”發生的準確時間為 12-07 的 23:59:59.47，如果計算精度的誤差為一秒，那麽該年大雪就有可能是 12-08 號而非 12-07 號。同樣的問題也會存在於合朔的確定上，如果合朔發生的時間距離兩個日期交接的時間非常近（23:59:59 或 00:00:01），那麽合朔具體的日期就變得難以確定，進而農曆月的起始就會出現誤差。

因此我想問一下作者是如何確定這一時間的呢？曆法規則上對此類特殊情況有沒有什麼特別的說明？謝謝！

**Comment by ytliu0** [comment]
您好!

首先要說的是我也是曆法愛好者，不是專業人士，我以前的專業是物理學和天文學，這使我在研習曆法上比較易上手，特別是對古今天文計算的認識或許比一般人較深入。

您問題很好，這情況在古代曆法尤其嚴重，因為古代的天文計算誤差較大，常遇到合朔和節氣時刻距午夜零時小於曆法的計算精度，曆官為了編曆必需制定法則處理這情況。據我的研究是古代曆官用當時行用的曆法計算時刻，算到在那天就在那天，不理會計算誤差。中國古代有時處於分裂局面，不同政權行用不同曆法，各曆法都有不同程度的誤差，遇到合朔和節氣時刻接近日界時，不同曆法可能會得出不一致的日期，因而各政權頒行的日曆有時有一日之差，所以拙網站在分裂時代列出多個有曆日資料王朝的日曆。

關於月相和節氣的計算，一般人可能不知道將時刻計算準到毫秒在天文學上是沒有意義的。節氣涉及太陽視黃經，月相涉及日月視黃經之差，黃經涉及黃道和春分點的定義。兩者因受到行星對地球的重力攝動及地球自轉軸的運動而不斷移動，其中地球自轉軸的運動還有不規則的成分，現代天文學為了給出準確黃道及春分點的定義，人為地忽略了不規則的成分及短週期的運動，只是取平均值。這些忽略了的運動效應雖然微小，但是如果要求月相和節氣時刻算準到一秒，如何取平均值變得十分重要，用不同的方法取平均值就會得出不同的結果。

當然，曆法為了處理合朔和節氣時刻非常接近午夜零時的情況，不得不將月相和節氣時刻的計算精度提高，2017年發佈的《農曆的編算頒行》文件規定要將時刻算準到一秒。要達到此精度必須言明上述的平均值如何計算，所以文件說要依國際地球自轉和參考系服務規範(IERS)發佈的文件計算，而這些平均值的計算方法有一部分是人為選取的，並無實際的天文意義，而且地球自轉的不均勻使現代曆法採用的時間標準UTC+8也要用實測數據再配合人為的閏秒制度決定，因此數十年後的月相和節氣UTC+8時刻現在只能確定到數秒的精度。這點我在[此網頁](https://ytliu0.github.io/ChineseCalendar/rules_chinese.html#newStandard)結尾也有提及。

回到您的問題，如上述，數十年後月相和節氣的UTC+8時刻因地球自轉不均勻現在只能算準到數秒，而且越往後誤差越大。如果預推的合朔和節氣的UTC+8時刻非常接近午夜零時，我們只能承認現在無法斷定這些合朔和節氣的日期，這就是拙網站的處理方法。我在[此網頁](https://ytliu0.github.io/ChineseCalendar/computation_chinese.html)說到在2050-2200年間，有六個合朔時刻因接近日界而日期暫時無法斷定，也有十一個節氣日期暫時無法斷定。

《農曆的編算頒行》明確說明中國科學院會提前一年正式發佈農曆日曆的年度標準資料。也就是說在中國大陸，現行農曆日曆的標準由中國科學院紫金山天文臺提前一年編算和頒行，臺灣的情況我不大清礎，估計是按臺灣中央氣象局的計算吧，至於古代的中曆日期則由當時的欽天監用當時行用的曆法編算和頒行。由於他們是提前一年才編算正式的日曆(非正式的日曆雖然在清朝預推二百年，但後來常修改預推的日期)，現代的合朔和節氣的時刻可算到至少一秒鐘的精度，如果時刻發生在日界附近，我估計他們會按既定的算法得出的時刻決定日期。也就是說如果他們算出的時間為12-07的 23:59:59.47，則定為12-07，如果他們算出的時刻是12-08的00:00:00.01，則定為12-08。如上述，準確到一秒的時刻並無實際天文意義，很大程度上是人為規定，所以在這情況下取12-07或12-08也在很大程度上是人為規定。

簡言之，古代曆法由當時的曆官編算和頒行，現在在中國大陸則由紫金山天文臺編算和頒行，他們按當時採用的曆法規則計算合朔和節氣時刻，算到在那天就在那天，不理會算出時刻的誤差。拙網站的處理方法是過去的日曆按照官方頒行的資料，未來的日曆則按《農曆的編算頒行》所述的方法編算，遇到合朔和節氣非常接近日界的情況就坦白說現在暫時無法斷定這些合朔和節氣的日期。

**Comment by ghost** [comment]
非常感謝作者百忙之中抽空解惑，之前在研究希伯來曆和藏曆時就有此類疑惑，因為大多數曆法最小單位為“日”，如果曆法是嚴格按照太陽或月亮的運動規律來計算，那麽在誤差必然存在的條件下就一定會出現這種位於兩個日期交界處的不確定，感覺這是無可避免的，此問題困擾我很久，現在看來也是自擾了，糾結這類誤差並無太大意義。

根據作者的解答，依據天體運動規律制定的曆法，不管是現行曆法還是歷史曆法，都會存在兩種影響因子，一種是根據規律計算，一種是歷官人為干預。對於現行曆法，如有官方的定義則以官方的為準，對於歷史曆法則以重要的歷史節點為準幷以推算作為參考，對於未來的曆法以及年代久遠無法參考歷史節點的則是推算為準。當然，非依據天體運動規律制定的曆法（如阿兹特克历）就不會有這樣的問題。

最後還是要感謝作者整理和提供的農曆相關資料，我在研究中國農曆查閱過不少資料，中國大陸的比較完善的是官方出版的一些參考文檔和許劍偉先生的壽星萬年曆和其提供的相關頁面資料，因為時間也相當久遠了，許先生的很多頁面資料已經沒有維護導致缺失，而海外的資料則更多偏向於類似 NASA 的行星運動規律計算，稍微全面點的相當稀缺。作者整理的相關資料是我能搜尋到的最新最全面的了，感謝！
