### ISSUE TITLE
想請教下作者提供的文檔中公式的問題

### ISSUE THREAD

**Issue by ghost** [ytliu0/ChineseCalendar#8]
我在查閱作者提供的[文檔](https://ytliu0.github.io/ChineseCalendar/docs/sunMoon_simp.pdf)時，發現在式(41)下您有提供地心視黃經的公式 λ = arg(Xec +iYec)，但是並沒有在文檔中找到實數 Yec 的定義，想問下您 Yec 的具體含義是什麽？謝謝。

**Comment by ytliu0** [comment]
粗體**Xec** 是三維向量，有三個分量。如下圖所示，第一個分量是Xec，第二個分量是Yec。

![Image1](https://user-images.githubusercontent.com/27743108/82977553-d6c7e200-9fa7-11ea-96ff-d30e04ffbc45.png)

**Comment by ghost** [comment]
原來如此，我忽略了粗體的變化。謝謝解答！
